// Code generated by protoc-gen-go. DO NOT EDIT.
// source: portmap/portmap.proto

package stratum_testing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry_PortType int32

const (
	Entry_IN_OUT Entry_PortType = 0
	Entry_IN     Entry_PortType = 1
	Entry_OUT    Entry_PortType = 2
)

var Entry_PortType_name = map[int32]string{
	0: "IN_OUT",
	1: "IN",
	2: "OUT",
}

var Entry_PortType_value = map[string]int32{
	"IN_OUT": 0,
	"IN":     1,
	"OUT":    2,
}

func (x Entry_PortType) String() string {
	return proto.EnumName(Entry_PortType_name, int32(x))
}

func (Entry_PortType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2f45ffb29594104, []int{0, 0}
}

type Entry struct {
	PortNumber           int32          `protobuf:"varint,1,opt,name=port_number,json=portNumber,proto3" json:"port_number,omitempty"`
	InterfaceName        string         `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	PortType             Entry_PortType `protobuf:"varint,3,opt,name=port_type,json=portType,proto3,enum=stratum.testing.Entry_PortType" json:"port_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2f45ffb29594104, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetPortNumber() int32 {
	if m != nil {
		return m.PortNumber
	}
	return 0
}

func (m *Entry) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *Entry) GetPortType() Entry_PortType {
	if m != nil {
		return m.PortType
	}
	return Entry_IN_OUT
}

type PortMap struct {
	Entries              []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortMap) Reset()         { *m = PortMap{} }
func (m *PortMap) String() string { return proto.CompactTextString(m) }
func (*PortMap) ProtoMessage()    {}
func (*PortMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2f45ffb29594104, []int{1}
}

func (m *PortMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortMap.Unmarshal(m, b)
}
func (m *PortMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortMap.Marshal(b, m, deterministic)
}
func (m *PortMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortMap.Merge(m, src)
}
func (m *PortMap) XXX_Size() int {
	return xxx_messageInfo_PortMap.Size(m)
}
func (m *PortMap) XXX_DiscardUnknown() {
	xxx_messageInfo_PortMap.DiscardUnknown(m)
}

var xxx_messageInfo_PortMap proto.InternalMessageInfo

func (m *PortMap) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterEnum("stratum.testing.Entry_PortType", Entry_PortType_name, Entry_PortType_value)
	proto.RegisterType((*Entry)(nil), "stratum.testing.Entry")
	proto.RegisterType((*PortMap)(nil), "stratum.testing.PortMap")
}

func init() { proto.RegisterFile("portmap/portmap.proto", fileDescriptor_c2f45ffb29594104) }

var fileDescriptor_c2f45ffb29594104 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x40, 0xdd, 0x84, 0x26, 0xed, 0x14, 0x6b, 0x19, 0x50, 0x72, 0x6b, 0x08, 0x88, 0x39, 0xad,
	0x52, 0x8f, 0x7a, 0xf5, 0xd0, 0x83, 0x51, 0x42, 0x3d, 0x87, 0xad, 0x8c, 0x92, 0xc3, 0x6e, 0x96,
	0xc9, 0xf4, 0x90, 0x1f, 0xf3, 0xfb, 0x24, 0x4b, 0xe3, 0x41, 0x7a, 0x9a, 0xe1, 0xf1, 0x98, 0x07,
	0x03, 0xd7, 0xbe, 0x63, 0xb1, 0xc6, 0xdf, 0x9f, 0xa6, 0xf6, 0xdc, 0x49, 0x87, 0x57, 0xbd, 0xb0,
	0x91, 0xa3, 0xd5, 0x42, 0xbd, 0xb4, 0xee, 0xbb, 0xf8, 0x51, 0x30, 0x7b, 0x71, 0xc2, 0x03, 0x6e,
	0x60, 0x39, 0xba, 0x8d, 0x3b, 0xda, 0x03, 0x71, 0xa6, 0x72, 0x55, 0xce, 0x6a, 0x18, 0x51, 0x15,
	0x08, 0xde, 0xc2, 0xaa, 0x75, 0x42, 0xfc, 0x65, 0x3e, 0xa9, 0x71, 0xc6, 0x52, 0x16, 0xe5, 0xaa,
	0x5c, 0xd4, 0x97, 0x7f, 0xb4, 0x32, 0x96, 0xf0, 0x19, 0x16, 0xe1, 0x8e, 0x0c, 0x9e, 0xb2, 0x38,
	0x57, 0xe5, 0x6a, 0xbb, 0xd1, 0xff, 0xb2, 0x3a, 0x24, 0xf5, 0x7b, 0xc7, 0xb2, 0x1f, 0x3c, 0xd5,
	0x73, 0x7f, 0xda, 0x8a, 0x3b, 0x98, 0x4f, 0x14, 0x01, 0x92, 0x5d, 0xd5, 0xbc, 0x7d, 0xec, 0xd7,
	0x17, 0x98, 0x40, 0xb4, 0xab, 0xd6, 0x0a, 0x53, 0x88, 0x47, 0x10, 0x15, 0x4f, 0x90, 0x8e, 0xe2,
	0xab, 0xf1, 0xf8, 0x00, 0x29, 0x39, 0xe1, 0x96, 0xfa, 0x4c, 0xe5, 0x71, 0xb9, 0xdc, 0xde, 0x9c,
	0xef, 0xd5, 0x93, 0x76, 0x48, 0xc2, 0x37, 0x1e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x5d,
	0x40, 0x3a, 0x26, 0x01, 0x00, 0x00,
}
