//
// Copyright 2019-present Open Networking Foundation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.9.1
// source: portmap/portmap.proto

package portmap

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Entry_PortType int32

const (
	Entry_IN_OUT Entry_PortType = 0 // This port could be used as ingress/egress to switch
	Entry_IN     Entry_PortType = 1 // This port could only be used as ingress to switch
	Entry_OUT    Entry_PortType = 2 // This port could only be used as egress to switch
)

// Enum value maps for Entry_PortType.
var (
	Entry_PortType_name = map[int32]string{
		0: "IN_OUT",
		1: "IN",
		2: "OUT",
	}
	Entry_PortType_value = map[string]int32{
		"IN_OUT": 0,
		"IN":     1,
		"OUT":    2,
	}
)

func (x Entry_PortType) Enum() *Entry_PortType {
	p := new(Entry_PortType)
	*p = x
	return p
}

func (x Entry_PortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Entry_PortType) Descriptor() protoreflect.EnumDescriptor {
	return file_portmap_portmap_proto_enumTypes[0].Descriptor()
}

func (Entry_PortType) Type() protoreflect.EnumType {
	return &file_portmap_portmap_proto_enumTypes[0]
}

func (x Entry_PortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Entry_PortType.Descriptor instead.
func (Entry_PortType) EnumDescriptor() ([]byte, []int) {
	return file_portmap_portmap_proto_rawDescGZIP(), []int{0, 0}
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PortNumber    uint32         `protobuf:"varint,1,opt,name=port_number,json=portNumber,proto3" json:"port_number,omitempty"`
	InterfaceName string         `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	PortType      Entry_PortType `protobuf:"varint,3,opt,name=port_type,json=portType,proto3,enum=stratum.testing.Entry_PortType" json:"port_type,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portmap_portmap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_portmap_portmap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_portmap_portmap_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetPortNumber() uint32 {
	if x != nil {
		return x.PortNumber
	}
	return 0
}

func (x *Entry) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *Entry) GetPortType() Entry_PortType {
	if x != nil {
		return x.PortType
	}
	return Entry_IN_OUT
}

type PortMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *PortMap) Reset() {
	*x = PortMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portmap_portmap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMap) ProtoMessage() {}

func (x *PortMap) ProtoReflect() protoreflect.Message {
	mi := &file_portmap_portmap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMap.ProtoReflect.Descriptor instead.
func (*PortMap) Descriptor() ([]byte, []int) {
	return file_portmap_portmap_proto_rawDescGZIP(), []int{1}
}

func (x *PortMap) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_portmap_portmap_proto protoreflect.FileDescriptor

var file_portmap_portmap_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6f, 0x72, 0x74, 0x6d, 0x61, 0x70, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x6d, 0x61,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x22, 0xb6, 0x01, 0x0a, 0x05, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08,
	0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x27, 0x0a, 0x08, 0x50, 0x6f, 0x72, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x5f, 0x4f, 0x55, 0x54, 0x10, 0x00,
	0x12, 0x06, 0x0a, 0x02, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x55, 0x54, 0x10,
	0x02, 0x22, 0x3b, 0x0a, 0x07, 0x50, 0x6f, 0x72, 0x74, 0x4d, 0x61, 0x70, 0x12, 0x30, 0x0a, 0x07,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x2e,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x75, 0x6d, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x6d, 0x61, 0x70, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_portmap_portmap_proto_rawDescOnce sync.Once
	file_portmap_portmap_proto_rawDescData = file_portmap_portmap_proto_rawDesc
)

func file_portmap_portmap_proto_rawDescGZIP() []byte {
	file_portmap_portmap_proto_rawDescOnce.Do(func() {
		file_portmap_portmap_proto_rawDescData = protoimpl.X.CompressGZIP(file_portmap_portmap_proto_rawDescData)
	})
	return file_portmap_portmap_proto_rawDescData
}

var file_portmap_portmap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_portmap_portmap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_portmap_portmap_proto_goTypes = []interface{}{
	(Entry_PortType)(0), // 0: stratum.testing.Entry.PortType
	(*Entry)(nil),       // 1: stratum.testing.Entry
	(*PortMap)(nil),     // 2: stratum.testing.PortMap
}
var file_portmap_portmap_proto_depIdxs = []int32{
	0, // 0: stratum.testing.Entry.port_type:type_name -> stratum.testing.Entry.PortType
	1, // 1: stratum.testing.PortMap.entries:type_name -> stratum.testing.Entry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_portmap_portmap_proto_init() }
func file_portmap_portmap_proto_init() {
	if File_portmap_portmap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_portmap_portmap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portmap_portmap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_portmap_portmap_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_portmap_portmap_proto_goTypes,
		DependencyIndexes: file_portmap_portmap_proto_depIdxs,
		EnumInfos:         file_portmap_portmap_proto_enumTypes,
		MessageInfos:      file_portmap_portmap_proto_msgTypes,
	}.Build()
	File_portmap_portmap_proto = out.File
	file_portmap_portmap_proto_rawDesc = nil
	file_portmap_portmap_proto_goTypes = nil
	file_portmap_portmap_proto_depIdxs = nil
}
